/**
 * Copyright 2020-2024 Jörn Berkefeld / joern.berkefeld@gmail.com
 *
 * Licensed under the MIT License.
 */

const eslintConfigSsjs = {
	meta: {},
	configs: {},
	rules: {},
	processors: {},
};

// assign configs here so we can reference `plugin`
Object.assign(eslintConfigSsjs.configs, {
	recommended: {
		languageOptions: {
			ecmaVersion: 3,
			sourceType: 'script',
			globals: {
				Account: 'readonly',
				AccountUser: 'readonly',
				Attribute: 'readonly',
				Base64Decode: 'readonly',
				Base64Encode: 'readonly',
				BeginImpressionRegion: 'readonly',
				BounceEvent: 'readonly',
				ContentArea: 'readonly',
				ContentAreaByName: 'readonly',
				ContentAreaObj: 'readonly',
				DataExtension: 'readonly',
				DateTime: 'readonly',
				DeliveryProfile: 'readonly',
				Email: 'readonly',
				EndImpressionRegion: 'readonly',
				FilterDefinition: 'readonly',
				Folder: 'readonly',
				Format: 'readonly',
				HTTP: 'readonly',
				HTTPHeader: 'readonly',
				List: 'readonly',
				Logout: 'readonly',
				Now: 'readonly',
				Platform: 'readonly',
				Portfolio: 'readonly',
				QueryDefinition: 'readonly',
				Redirect: 'readonly',
				Request: 'readonly',
				Script: 'readonly',
				Send: 'readonly',
				SendClassification: 'readonly',
				SenderProfile: 'readonly',
				Stringify: 'readonly',
				Subscriber: 'readonly',
				Substring: 'readonly',
				Template: 'readonly',
				TriggeredSend: 'readonly',
				Variable: 'readonly',
				Write: 'readonly',
			},
		},
		rules: {
			'comma-dangle': ['error', 'never'],
			'new-cap': 'off',
			'no-console': 'off',
			'no-extend-native': 'off',
			'no-new': 'error',
			'no-prototype-builtins': 'off',
			'no-throw-literal': 'off',
			'no-use-before-define': ['error', { variables: true, functions: false, classes: false }],
			'no-var': 'off',
		},
	},
	legacy: {
		recommended: {
			overrides: [
				{
					files: ['*.ssjs'],
					parserOptions: {
						ecmaVersion: 3,
					},
					rules: {
						'comma-dangle': ['error', 'never'],
						'new-cap': 'off',
						'no-console': 'off',
						'no-extend-native': 'off',
						'no-new': 'error',
						'no-prototype-builtins': 'off',
						'no-throw-literal': 'off',
						'no-use-before-define': ['error', { variables: true, functions: false, classes: false }],
						'no-var': 'off',
					},
					globals: {
						Account: false,
						AccountUser: false,
						Attribute: false,
						Base64Decode: false,
						Base64Encode: false,
						BeginImpressionRegion: false,
						BounceEvent: false,
						ContentArea: false,
						ContentAreaByName: false,
						ContentAreaObj: false,
						DataExtension: false,
						DateTime: false,
						DeliveryProfile: false,
						Email: false,
						EndImpressionRegion: false,
						FilterDefinition: false,
						Folder: false,
						Format: false,
						HTTP: false,
						HTTPHeader: false,
						List: false,
						Logout: false,
						Now: false,
						Platform: false,
						Portfolio: false,
						QueryDefinition: false,
						Redirect: false,
						Request: false,
						Script: false,
						Send: false,
						SendClassification: false,
						SenderProfile: false,
						Stringify: false,
						Subscriber: false,
						Substring: false,
						Template: false,
						TriggeredSend: false,
						Variable: false,
						Write: false,
					},
				},
			],
		},
	},
});

// for CommonJS
module.exports = eslintConfigSsjs;
